services:
  postgres:
    image: postgres:16-alpine
    container_name: parchmark-postgres
    environment:
      POSTGRES_USER: parchmark_user
      POSTGRES_PASSWORD: parchmark_password
      POSTGRES_DB: parchmark_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parchmark_user -d parchmark_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - parchmark-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.docker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parchmark-net

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./ui/.env.docker
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - parchmark-net

volumes:
  postgres_data:

networks:
  parchmark-net:
    driver: bridge
