services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    restart: unless-stopped
