repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff
        args: [--no-fix]  # Only check, don't auto-fix
      - id: ruff-format
        args: [--check]  # Only check formatting, don't auto-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        files: ^app/.*\.py$
        additional_dependencies: [
          "fastapi==0.104.1",
          "sqlalchemy>=2.0.32",
          "pydantic>=2.0",
          "python-jose[cryptography]==3.3.0",
          "passlib[bcrypt]==1.7.4",
          "python-multipart==0.0.6",
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
        exclude: 'tsconfig.*\.json$'  # Exclude tsconfig files which allow comments
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
