"""add indexes for user_id username oidc_sub

Revision ID: 170dd30cebde
Revises: 3c1162fce719
Create Date: 2026-01-29 16:43:41.388355

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "170dd30cebde"
down_revision: str | Sequence[str] | None = "3c1162fce719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    # ### end Alembic commands ###
