services:
  parchmark-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - '9090:80' not needed as services are on proxiable network exposing original ports
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - proxiable
networks:
  proxiable:
    external: true
    name: proxiable
